"""referral_code

Revision ID: cf0fc95b24da
Revises: f7b23a37c516
Create Date: 2024-02-13 07:23:01.442196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0fc95b24da'
down_revision = 'f7b23a37c516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_code', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('referral_expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'referral_expiration')
    op.drop_column('user', 'referral_code')
    # ### end Alembic commands ###
